schemaVersion: 1
enabledWorkflows:
  - simulator
  - coverage
  - debugging
  - device
  - doctor
  - logging
  - project-discovery
  - project-scaffolding
  - simulator-management
  - swift-package
  - ui-automation
  - utilities
  - xcode-ide
debug: true
sentryDisabled: false
sessionDefaults:
  projectPath: libixlandTest/libixlandTest/libixlandTest.xcodeproj
  scheme: libixlandTest
  deviceId: 7F8A1701-D612-5A9C-AAE7-8FD0AD77306C
  simulatorId: A34273D2-BCBB-4900-BAAF-09AF75144636
  simulatorName: iPhone 17 Pro
